site_name: DSPerf
site_description: Network Performance Testing
site_url: http://localhost:8004/

theme:
  name: material
  features:
    - navigation.sidebar
    - search.highlight
  palette:
    - scheme: default
      primary: teal

nav:
  - Home: index.md
  - Overview: overview.md
  - Options: options.md
  - Compliance: compliance.md
  - Test Case: test-case.md

plugins:
  - search

extra_css:
  - ../docs/stylesheets/extra.css

copyright: |
  <a href="http://localhost:8000/" style="color: #c13725; font-weight: 600;">← Back to Main Site</a>